/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import spravca.Spravca;
import gui.PridanieObjektu;
import gui.ZoznamNehnutelnosti;

/**
 *
 * @author Jozef
 */
public class Menu extends javax.swing.JFrame {
    
    
    private static Spravca instancia;
    /**
     * Creates new form Menu
     */
    public Menu(Spravca paInstancia) {
        initComponents();
        if (paInstancia != null) {
            this.instancia = paInstancia;
        } else {
            this.instancia = new Spravca();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pridatNehnutelnost = new javax.swing.JButton();
        zobrazitNehnutelnosti = new javax.swing.JButton();
        zobrazitParcely = new javax.swing.JButton();
        generuj = new javax.swing.JButton();
        zapis = new javax.swing.JButton();
        citac = new javax.swing.JButton();
        zobrazitParcely1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        pridatNehnutelnost.setBackground(new java.awt.Color(204, 204, 0));
        pridatNehnutelnost.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pridatNehnutelnost.setText("Pridať nový objekt");
        pridatNehnutelnost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridatNehnutelnostActionPerformed(evt);
            }
        });

        zobrazitNehnutelnosti.setBackground(new java.awt.Color(204, 204, 0));
        zobrazitNehnutelnosti.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        zobrazitNehnutelnosti.setText("Zobraziť nehnuteľnosti");
        zobrazitNehnutelnosti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zobrazitNehnutelnostiActionPerformed(evt);
            }
        });

        zobrazitParcely.setBackground(new java.awt.Color(204, 204, 0));
        zobrazitParcely.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        zobrazitParcely.setText("Zobraziť parcely");
        zobrazitParcely.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zobrazitParcelyActionPerformed(evt);
            }
        });

        generuj.setBackground(new java.awt.Color(204, 204, 0));
        generuj.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        generuj.setText("Generovanie záznamov");
        generuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generujActionPerformed(evt);
            }
        });

        zapis.setBackground(new java.awt.Color(204, 204, 0));
        zapis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        zapis.setText("Zápis do súboru");
        zapis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zapisActionPerformed(evt);
            }
        });

        citac.setBackground(new java.awt.Color(204, 204, 0));
        citac.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        citac.setText("Čítanie zo súboru");
        citac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citacActionPerformed(evt);
            }
        });

        zobrazitParcely1.setBackground(new java.awt.Color(204, 204, 0));
        zobrazitParcely1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        zobrazitParcely1.setText("Zobraziť všetky objekty");
        zobrazitParcely1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zobrazitParcely1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pridatNehnutelnost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zobrazitNehnutelnosti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zobrazitParcely, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(generuj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zapis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(citac, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zobrazitParcely1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(140, 140, 140))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(pridatNehnutelnost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(zobrazitNehnutelnosti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(zobrazitParcely)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(zobrazitParcely1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(generuj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(zapis, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(citac)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pridatNehnutelnostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridatNehnutelnostActionPerformed
        this.setVisible(false);
        PridanieObjektu okno = new PridanieObjektu(this.instancia);
        okno.setVisible(true);
    }//GEN-LAST:event_pridatNehnutelnostActionPerformed

    private void zobrazitNehnutelnostiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zobrazitNehnutelnostiActionPerformed
        ZoznamNehnutelnosti zn = new ZoznamNehnutelnosti(instancia);
        this.setVisible(false);
        zn.setVisible(true);
    }//GEN-LAST:event_zobrazitNehnutelnostiActionPerformed

    private void zobrazitParcelyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zobrazitParcelyActionPerformed
        ZoznamParciel zn = new ZoznamParciel(instancia);
        this.setVisible(false);
        zn.setVisible(true);
    }//GEN-LAST:event_zobrazitParcelyActionPerformed

    private void generujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generujActionPerformed
        Generovanie zn = new Generovanie(instancia);
        this.setVisible(false);
        zn.setVisible(true);
    }//GEN-LAST:event_generujActionPerformed

    private void zapisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zapisActionPerformed
        instancia.zapisNehnutelnosti();
        instancia.zapisParcely();
    }//GEN-LAST:event_zapisActionPerformed

    private void citacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citacActionPerformed
        instancia.citajNehnutelnosti();
        instancia.citajParcely();
    }//GEN-LAST:event_citacActionPerformed

    private void zobrazitParcely1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zobrazitParcely1ActionPerformed
        ZoznamVsetkych zn = new ZoznamVsetkych(instancia);
        this.setVisible(false);
        zn.setVisible(true);
    }//GEN-LAST:event_zobrazitParcely1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu(instancia).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton citac;
    private javax.swing.JButton generuj;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pridatNehnutelnost;
    private javax.swing.JButton zapis;
    private javax.swing.JButton zobrazitNehnutelnosti;
    private javax.swing.JButton zobrazitParcely;
    private javax.swing.JButton zobrazitParcely1;
    // End of variables declaration//GEN-END:variables
}
