/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import spravca.Spravca;
import datova_cast.Nehnutelnost;
import datova_cast.Parcela;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import strom.Kluc;
import strom.Porovnatelne;
import strom.Vrchol;

/**
 *
 * @author Jozef
 */
public class ZoznamVsetkych extends javax.swing.JFrame {
    private static Spravca instancia;
    private ArrayList<Vrchol> zoznamNajdenych;
    /**
     * Creates new form ZoznamVsetkych
     */
    public ZoznamVsetkych(Spravca paInstancia) {
        initComponents();
        this.instancia = paInstancia;
    }
    
    public void vyplnTabulkuNehnutelnosti() {

        double doleX = Double.parseDouble(dolneX.getText());
        double horeX = Double.parseDouble(horneX.getText());
        double doleY = Double.parseDouble(dolneY.getText());
        double horeY = Double.parseDouble(horneY.getText());
        
        double[] poleSuradnic = {doleX, horeX, doleY, horeY};
        
        ArrayList<Vrchol> zoznamNehnutelnosti = instancia.najdiNehnutelnostiNaGPS(poleSuradnic);
        ArrayList<Vrchol> zoznamParciel = instancia.najdiParcelyNaGPS(poleSuradnic);
        
        DefaultTableModel model = (DefaultTableModel) tabulkaNehnutelnosti.getModel();
        
        while(model.getRowCount() > 0) {
            model.removeRow(0);
        }
        
        int pocitadlo = 0;
        if (zoznamNehnutelnosti != null) {
            for (Vrchol akt : zoznamNehnutelnosti) {
                pocitadlo = pocitadlo + 1;
                model.addRow(new Object[]{pocitadlo, akt.dajKlucNaIndexe(0).dajHodnotuKluca(), akt.dajNehnutelnost().dajSirku(), akt.dajKlucNaIndexe(1).dajHodnotuKluca(), akt.dajNehnutelnost().dajDlzku(), akt.dajNehnutelnost().dajSupisneCislo(), akt.dajNehnutelnost().dajPopis()});
            }
        }
        
        if (zoznamParciel != null) {
            for (Vrchol akt : zoznamParciel) {
                pocitadlo = pocitadlo + 1;
                model.addRow(new Object[]{pocitadlo, akt.dajKlucNaIndexe(0).dajHodnotuKluca(), akt.dajNehnutelnost().dajSirku(), akt.dajKlucNaIndexe(1).dajHodnotuKluca(), akt.dajNehnutelnost().dajDlzku(), akt.dajNehnutelnost().dajSupisneCislo(), akt.dajNehnutelnost().dajPopis()});
            }
        }
        
        this.zoznamNajdenych = zoznamNehnutelnosti;
        this.zoznamNajdenych.addAll(zoznamParciel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dolneX = new javax.swing.JTextField();
        dolneY = new javax.swing.JTextField();
        horneX = new javax.swing.JTextField();
        horneY = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabulkaNehnutelnosti = new javax.swing.JTable();
        vyhladat = new javax.swing.JButton();
        hlavneMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Zadajte dolné X:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Zadajte horné X:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Zadajte dolné Y:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Zadajte horné Y:");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Vyhľadanie všetkých objektov:");

        tabulkaNehnutelnosti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Súradnica X", "E/W", "Súradnica Y", "N/S", "Súpisné číslo", "Popis"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabulkaNehnutelnosti);

        vyhladat.setText("Vyhľadať");
        vyhladat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vyhladatActionPerformed(evt);
            }
        });

        hlavneMenu.setText("Hlavné menu");
        hlavneMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hlavneMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(dolneY, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(dolneX, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel2)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(horneX, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(horneY, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(234, 234, 234)
                                .addComponent(vyhladat)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(39, 39, 39)
                                .addComponent(hlavneMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(hlavneMenu))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(dolneX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horneX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(dolneY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(horneY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(vyhladat)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vyhladatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vyhladatActionPerformed
        this.vyplnTabulkuNehnutelnosti();
    }//GEN-LAST:event_vyhladatActionPerformed

    private void hlavneMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hlavneMenuActionPerformed
        this.setVisible(false);
        Menu hm = new Menu(instancia);
        hm.setVisible(true);
    }//GEN-LAST:event_hlavneMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZoznamVsetkych.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZoznamVsetkych.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZoznamVsetkych.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZoznamVsetkych.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZoznamVsetkych(instancia).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dolneX;
    private javax.swing.JTextField dolneY;
    private javax.swing.JButton hlavneMenu;
    private javax.swing.JTextField horneX;
    private javax.swing.JTextField horneY;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabulkaNehnutelnosti;
    private javax.swing.JButton vyhladat;
    // End of variables declaration//GEN-END:variables
}
